name: Deploy to Cloud Run

on:
  push:
    branches: ['main']

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: deploy to Cloud Run
    runs-on: ubuntu-latest

    steps:
#      - name: checkout repository
#        uses: actions/checkout@v7

      - name: Authentication
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUT_EMAIL }}

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker asia-northeast1-docker.pkg.dev

      - name: Build Docker Image
        run: docker build -t asia-northeast1-docker.pkg.dev/project-45aec6c7-f1de-4e00-ab3/my-first-repo/github-actions-sample:${{ github.sha }} .

      - name: Push Docker image
        run: docker push asia-northeast1-docker.pkg.dev/project-45aec6c7-f1de-4e00-ab3/my-first-repo/github-actions-sample:${{ github.sha }}

      - name: Deploy to Cloud Run
        uses:  google-github-actions/deploy-cloudrun@v2
        with:
          service: github-actions-sample-app
          region: asia-northeast1
          image: asia-northeast1-docker.pkg.dev/project-45aec6c7-f1de-4e00-ab3/my-first-repo/github-actions-sample:${{ github.sha }}